### PR TITLE
Solidarity economy initiatives schema: draft

### PR DESCRIPTION
**Pull request by wu-lee**
This is a first draft, and I've written some code to generate JSON files with matching schemas, example published here:

https://dev.data.solidarityeconomy.coop/sea-lod/oxford/65.murm.json

I've only used existing fields for now. We might look at new field types when this is working otherwise, as well as annotating it with json-ld tags.

But the next thing is to see if we can get Murmurations consuming the 170-odd initiatives in the Solidarity Oxford dataset, on URLs like https://dev.lod.coop/sea-lod/oxford/65.murm.json (redirection rules need to be adjusted first).

### CODE REVIEW

**Comment by wu-lee** [comment]
Note, `.editorconfig` not strictly part of this pull request, not sure whether to submit a separate PR for that?

**Comment by wu-lee** [comment]
I've just amended the PR to:
- use integer version numbers
- remove illegal comments from .json
- include a dummy `metadata.schema.url` property pending consultation, because there seems to be no suitable URL for this schema

**Comment by wu-lee** [comment]
Some discussion here: https://murmurations.flarum.cloud/d/20-schema-metadata-what-should-it-be/4

**Review by olisb — COMMENTED** [review]
RE:       "url": "http://example.com/what-to-use-here?",

Make a page on your site like: https://www.solidarityeconomy.coop/murmurations-schema which explains as much as you like about your schema: what it's for, what plans there are to expand it, who should use it etc etc, then link to that ;)

**Comment by wu-lee** [comment]
I've just edited the schema and re-pushed it.  Changes are:
- correct spelling of "initative"
- add `linked_schemas` field, copy-pasted from `default-v1.json`
- add a `propertyNames` constraint, copy-pasted from `default-v1.json`
- add a description URL backed with an actual description

**Review by olisb — CHANGES_REQUESTED** [review]
"linked_schemas"  should also be added to "required"
I'm not sure you need the "propertyNames" pattern - but equally don't think it can hurt ;)

**Comment by wu-lee** [comment]
> "linked_schemas" should also be added to "required"

done



> I'm not sure you need the "propertyNames" pattern - but equally don't think it can hurt ;)

I gather that it's an implicit constraint due to default-v1 being applied across the board - I thought I should make it explicit in the same way I'm making the other shared field constraints (linked_data, name, geolocation, etc.)  explicit.

**Review by olisb — APPROVED** [review]
looks good to me

**Pull request merged**
